name: esp32_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  json_annotation: ^4.9.0
  multicast_dns: ^0.3.3
  network_info_plus: ^7.0.0
  shared_preferences: ^2.5.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/casa-inteligente.png"

flutter:
  uses-material-design: true
